#!/bin/sh

#name=""
if [ ! -n "$1" ];then 
    name=$(date "+%Y-%m-%d-%H:%M:%S")
else
    name=$1
fi

echo "Finish Trajectory 0"
rosservice call /finish_trajectory 0
echo "Save pbstream"
rosservice call /write_state "{filename: '/home/lrd/map/$name.pbstream'}"
echo "Converting map"
rosrun cartographer_ros cartographer_pbstream_to_ros_map -map_filestem=/home/lrd/map/$name -pbstream_filename=/home/lrd/map/$name.pbstream -resolution=0.05
#touch $name.trans.yaml
python add_data.py /home/lrd/map/$name.trans.yaml
python calibration_map.py /home/lrd/map/$name.trans.yaml
